# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoccerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoccerApp
	
	pod 'SwiftyJSON', '~> 4.0'

  target 'SoccerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoccerAppUITests' do
    # Pods for testing
  end

end
